//USER
export const USER_START_LOADING = 'USER_START_LOADING';
export const USER_END_LOADING = 'USER_END_LOADING'; 

export const LOGIN = 'LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESSS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const GET_USER_DATA = 'GET_USER_DATA';
export const ADD_TO_NEWSLETTER = 'ADD_TO_NEWSLETTER';


//ADMIN
export const ADMIN_SUCCESS = 'ADMIN_SUCCESS';
export const ADMIN_FAILED = 'ADMIN_FAILED';


//POSTS
export const POSTS_START_LOADING = 'POST_START_LOADING';
export const POSTS_END_LOADING = 'POST_END_LOADING';

export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const GET_POPULAR_POST = 'GET_POPULAR_POST';
export const GET_NUMBER_OF_POSTS = 'GET_NUMBER_OF_POSTS';

export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';

export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAILED = 'EDIT_POST_FAILED';

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';

export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';


//POSTS - COMMENTS
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILED = 'DELETE_COMMENT_FAILED';

export const ADD_COMMENT_START = 'ADD_COMMENT_START';
export const ADD_COMMENT_END = 'ADD_COMMENT_END';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';